'use client'

import { useState } from 'react'
import { reports } from '@/lib/data'
import NewReportModal from '@/components/dashboard/reports/NewReportModal'

const typeStyles = {
  Collection: 'bg-blue-100 text-blue-700',
  Overdue: 'bg-red-100 text-red-600',
  Income: 'bg-green-100 text-green-700',
  Disbursement: 'bg-purple-100 text-purple-700',
  Customer: 'bg-orange-100 text-orange-600',
}

export default function ReportsPage() {
  const [showModal, setShowModal] = useState(false)
  const [search, setSearch] = useState('')

  const filtered = reports.filter(
    (r) =>
      r.title.toLowerCase().includes(search.toLowerCase()) ||
      r.type.toLowerCase().includes(search.toLowerCase())
  )

  return (
    <div>
      <div className="flex items-start justify-between mb-6 gap-4">
        <div>
          <h1 className="text-xl md:text-2xl font-bold text-gray-800">Reports</h1>
          <p className="text-gray-400 text-sm mt-1">Generate and view financial reports.</p>
        </div>
        <button
          onClick={() => setShowModal(true)}
          className="shrink-0 bg-green-600 text-white px-4 py-2 rounded-md text-sm font-medium hover:bg-green-700 transition"
        >
          + Generate Report
        </button>
      </div>

      {showModal && <NewReportModal onClose={() => setShowModal(false)} />}

      <div className="bg-white rounded-xl shadow-sm border border-gray-100">

        {/* Search */}
        <div className="p-4 border-b border-gray-100">
          <input
            type="text"
            placeholder="Search reports..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="border border-gray-200 rounded-md px-3 py-2 text-sm w-full md:w-72 focus:outline-none focus:ring-2 focus:ring-blue-300"
          />
        </div>

        {/* Mobile cards */}
        <div className="md:hidden divide-y divide-gray-100">
          {filtered.length === 0 ? (
            <p className="text-center text-gray-400 text-sm py-8">No reports found.</p>
          ) : (
            filtered.map((r) => (
              <div key={r.id} className="p-4 flex flex-col gap-2">
                <div className="flex items-start justify-between">
                  <p className="font-semibold text-gray-800 text-sm">{r.title}</p>
                  <span className={`px-2 py-1 rounded-full text-xs font-semibold shrink-0 ml-2 ${typeStyles[r.type]}`}>
                    {r.type}
                  </span>
                </div>
                <p className="text-xs text-gray-400">{r.id}</p>
                <p className="text-sm text-gray-600">Period: {r.period}</p>
                <p className="text-sm text-gray-600">Generated: {r.generatedDate}</p>
                <p className="text-xs text-gray-400">By: {r.generatedBy}</p>
                <div className="flex gap-2 mt-1">
                  <button className="text-xs bg-blue-50 text-blue-600 px-3 py-1 rounded-md hover:bg-blue-100 transition">
                    View
                  </button>
                  <button className="text-xs bg-gray-50 text-gray-600 px-3 py-1 rounded-md hover:bg-gray-100 transition">
                    Download
                  </button>
                </div>
              </div>
            ))
          )}
        </div>

        {/* Desktop table */}
        <div className="hidden md:block overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-gray-50 text-gray-500 uppercase text-xs">
              <tr>
                <th className="px-4 py-3 text-left">ID</th>
                <th className="px-4 py-3 text-left">Title</th>
                <th className="px-4 py-3 text-left">Type</th>
                <th className="px-4 py-3 text-left">Period</th>
                <th className="px-4 py-3 text-left">Generated Date</th>
                <th className="px-4 py-3 text-left">Generated By</th>
                <th className="px-4 py-3 text-left">Actions</th>
              </tr>
            </thead>
            <tbody>
              {filtered.length === 0 ? (
                <tr>
                  <td colSpan={7} className="text-center text-gray-400 py-8">
                    No reports found.
                  </td>
                </tr>
              ) : (
                filtered.map((r) => (
                  <tr key={r.id} className="border-t border-gray-100 hover:bg-gray-50">
                    <td className="px-4 py-3 text-gray-500">{r.id}</td>
                    <td className="px-4 py-3 font-medium text-gray-800">{r.title}</td>
                    <td className="px-4 py-3">
                      <span className={`px-2 py-1 rounded-full text-xs font-semibold ${typeStyles[r.type]}`}>
                        {r.type}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-gray-600">{r.period}</td>
                    <td className="px-4 py-3 text-gray-600">{r.generatedDate}</td>
                    <td className="px-4 py-3 text-gray-600">{r.generatedBy}</td>
                    <td className="px-4 py-3">
                      <div className="flex gap-2">
                        <button className="text-xs bg-blue-50 text-blue-600 px-3 py-1 rounded-md hover:bg-blue-100 transition">
                          View
                        </button>
                        <button className="text-xs bg-gray-50 text-gray-600 px-3 py-1 rounded-md hover:bg-gray-100 transition">
                          Download
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        <div className="px-4 py-3 text-xs text-gray-400 border-t border-gray-100 flex justify-between">
          <span>Showing {filtered.length} of {reports.length} results</span>
          <span>Page 1 of 1</span>
        </div>
      </div>
    </div>
  )
}