'use client'

import { useState } from 'react'
import { X } from 'lucide-react'
import { motion } from 'framer-motion'

export default function NewReportModal({ onClose }) {
  const [errors, setErrors] = useState({})
  const [form, setForm] = useState({
    title: '', type: '', period: '', generatedBy: '',
  })

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value })
    if (errors[e.target.name]) setErrors({ ...errors, [e.target.name]: '' })
  }

  const validate = () => {
    const newErrors = {}
    if (!form.title.trim()) newErrors.title = 'Report title is required'
    if (!form.type) newErrors.type = 'Report type is required'
    if (!form.period.trim()) newErrors.period = 'Period is required'
    if (!form.generatedBy.trim()) newErrors.generatedBy = 'Generated by is required'
    return newErrors
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    const validationErrors = validate()
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors)
      return
    }
    console.log('New report:', form)
    onClose()
  }

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4"
    >
      <motion.div
        initial={{ opacity: 0, scale: 0.95, y: 10 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: 10 }}
        transition={{ duration: 0.2 }}
        className="bg-white rounded-2xl shadow-xl w-full max-w-md"
      >
        <div className="flex items-center justify-between p-6 border-b border-gray-100">
          <h2 className="text-lg font-bold text-gray-800">Generate New Report</h2>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 transition-colors">
            <X size={20} />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-4">

          <div>
            <label htmlFor="rpt-title" className="block text-sm font-medium text-gray-700 mb-1">
              Report Title *
            </label>
            <input
              id="rpt-title" name="title" type="text"
              placeholder="e.g. Monthly Collection Report"
              value={form.title} onChange={handleChange}
              className={`w-full border rounded-lg px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-blue-400
                ${errors.title ? 'border-red-400 bg-red-50' : 'border-gray-200'}`}
            />
            {errors.title && <p className="text-red-500 text-xs mt-1">{errors.title}</p>}
          </div>

          <div>
            <label htmlFor="rpt-type" className="block text-sm font-medium text-gray-700 mb-1">
              Report Type *
            </label>
            <select
              id="rpt-type" name="type"
              value={form.type} onChange={handleChange}
              className={`w-full border rounded-lg px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-blue-400
                ${errors.type ? 'border-red-400 bg-red-50' : 'border-gray-200'}`}
            >
              <option value="">Select type</option>
              <option value="Collection">Collection</option>
              <option value="Overdue">Overdue</option>
              <option value="Income">Income</option>
              <option value="Disbursement">Disbursement</option>
              <option value="Customer">Customer</option>
            </select>
            {errors.type && <p className="text-red-500 text-xs mt-1">{errors.type}</p>}
          </div>

          <div>
            <label htmlFor="rpt-period" className="block text-sm font-medium text-gray-700 mb-1">
              Period *
            </label>
            <input
              id="rpt-period" name="period" type="text"
              placeholder="e.g. May 2026"
              value={form.period} onChange={handleChange}
              className={`w-full border rounded-lg px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-blue-400
                ${errors.period ? 'border-red-400 bg-red-50' : 'border-gray-200'}`}
            />
            {errors.period && <p className="text-red-500 text-xs mt-1">{errors.period}</p>}
          </div>

          <div>
            <label htmlFor="rpt-generatedby" className="block text-sm font-medium text-gray-700 mb-1">
              Generated By *
            </label>
            <input
              id="rpt-generatedby" name="generatedBy" type="text"
              placeholder="Enter your name"
              value={form.generatedBy} onChange={handleChange}
              className={`w-full border rounded-lg px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-blue-400
                ${errors.generatedBy ? 'border-red-400 bg-red-50' : 'border-gray-200'}`}
            />
            {errors.generatedBy && <p className="text-red-500 text-xs mt-1">{errors.generatedBy}</p>}
          </div>

          <div className="flex gap-3 pt-2">
            <button
              type="button" onClick={onClose}
              className="flex-1 border border-gray-200 text-gray-600 py-2 rounded-lg text-sm font-medium hover:bg-gray-50 transition-all duration-200 active:scale-95"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="flex-1 bg-green-600 text-white py-2 rounded-lg text-sm font-medium hover:bg-green-700 transition-all duration-200 active:scale-95"
            >
              Generate Report
            </button>
          </div>

        </form>
      </motion.div>
    </motion.div>
  )
}